CREATE TABLE IF NOT EXISTS `employees` (
  `id` varchar(20) NOT NULL PRIMARY KEY,
  `name` varchar(100) NOT NULL,
  `position` varchar(100) NOT NULL,
  `mobile` varchar(20) NOT NULL,
  `emp_status` enum('PROBATIONARY','REGULAR') NOT NULL,
  `appointed_as` varchar(100) NOT NULL,
  `birthdate` varchar(30) NOT NULL,
  `civil_status` varchar(20) NOT NULL,
  `address` varchar(150) NOT NULL, 
  `image` varchar(100) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `employees` (`id`, `name`, `position`, `mobile`, `emp_status`, `appointed_as`, `birthdate`, `civil_status`, `address`, `image`) VALUES
('JPMC-HRD-025', 'ROBIN NOMBRADO', 'PROCESS ENGINEER', '0945-2737-786', 'PROBATIONARY', 'SAFETY OFFICER/ MAINTENANCE OIC', 'APRIL 30, 1992', 'SINGLE', 'SILVERSTOWN 4, IMUS CAVITE', 'images/abs1.png'),
('JPMC-HRD-026', 'JONATHAN RAY. ANTIONIO', 'QA SUPERVISOR', '0912-3456-789', 'REGULAR', 'QUALITY CONTROL HEAD', 'MARCH 15, 1988', 'MARRIED', 'BACOOR, CAVITE', 'images/abs2.png'),
('JPMC-HRD-027', 'ALBERT B. ALACAPA', 'WAREHOUSEMAN', '0923-4567-890', 'REGULAR', 'INVENTORY CONTROLLER', 'JULY 22, 1990', 'SINGLE', 'DASMARIÑAS, CAVITE', 'images/abs3.png'),
('JPMC-HRD-028', 'MARDY AGUILAR', 'MOLD FABRICATOR', '0934-5678-901', 'REGULAR', 'PRODUCTION SPECIALIST', 'SEPTEMBER 8, 1985', 'MARRIED', 'GENERAL TRIAS, CAVITE', 'images/hips1.png'),
('JPMC-HRD-029', 'JOHN BRYAN FERRER', 'IT SUPERVISOR', '0945-6789-012', 'REGULAR', 'SYSTEMS ADMINISTRATOR', 'DECEMBER 3, 1987', 'SINGLE', 'IMUS, CAVITE', 'images/hips2.png'),
('JPMC-HRD-030', 'ANABEL E. PUNINCIAR', 'MACHINE OPERATOR', '0956-7890-123', 'PROBATIONARY', 'PRODUCTION OPERATOR', 'MAY 12, 1993', 'SINGLE', 'SILANG, CAVITE', 'images/hips3.png'),
('JPMC-HRD-031', 'RICKY V. TONGOL', 'MOLD FABRICATOR', '0967-8901-234', 'REGULAR', 'TECHNICAL SPECIALIST', 'AUGUST 19, 1989', 'MARRIED', 'TRECE MARTIRES, CAVITE', 'images/nylon1.png'),
('JPMC-HRD-032', 'VIRGINIA M. BRUN', 'MACHINE OPERATOR', '0978-9012-345', 'REGULAR', 'PRODUCTION OPERATOR', 'JANUARY 25, 1991', 'SINGLE', 'NAIC, CAVITE', 'images/nylon2.png'),
('JPMC-HRD-033', 'ZALDY P. ALFON', 'PRINTING OPERATOR', '0989-0123-456', 'REGULAR', 'PRINTING SPECIALIST', 'NOVEMBER 7, 1986', 'MARRIED', 'TANZA, CAVITE', 'images/nylon3.png');
